language: python
python:
      - "3.6"
sudo: false

branches:
   only:
     - master

env:
  global:
    - TWINE_USERNAME=MKoesters
    # Note: TWINE_PASSWORD is set in Travis settings

matrix:
  include:
    - python: 3.6
      env: TOXENV=test
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=code_format

script:
  - tox -e testenv,docs,code_format
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 setup.py sdist
      python3 setup.py bdist_wheel --universal
      pip3 install twine
      twine upload --repository-url https://test.pypi.org/legacy/ dist/*
    fi
