language: python
python:
      - "3.6"
sudo: false

env:
  global:
    - TWINE_USERNAME=MKoesters
    # Note: TWINE_PASSWORD is set in Travis settings

script:
  - tox
  - python3 setup.py sdist
  - python3 setup.py bdist_wheel --universal
  - pip3 install twine
  - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
