env:
  global:
    - TWINE_USERNAME=MKoesters
    # Note: TWINE_PASSWORD is set in Travis settings

deploy:
   provider: pypi
   server: https://testpypi.python.org/pypi

script:
  - pip install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload wheelhouse/*.whl
    fi
